<a href="https://colab.research.google.com/github/Bhavyagoyal04/Python-Codes/blob/main/Colab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list_1=[10,8,22,36,12,47,21]
max=max(list_1)
print(max)

47


In [ ]:
list_1=[]
c=0
for i in range(2,100):
  c=0
  for j in range(2,i):
    if i%j==0:
      c=c+1
  if c==0:
    list_1.append(i)
print(list_1)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [ ]:
list_1=[3,7,5,9,2,6]
a=list_1[0]
list_1[0]=list_1[5]
list_1[5]=a
print(list_1)

[6, 7, 5, 9, 2, 3]


In [ ]:
list_1=[1,1,1,5,3,9,6,8,7,9,3,7]
list_1.sort()
print(list_1)

[1, 1, 1, 3, 3, 5, 6, 7, 7, 8, 9, 9]


In [ ]:
def square(n):
  return n**2
def sum(a,b):
  square(a)
  return a+b
result=square
print(result(5))
summation=sum(10,7)
print(summation)

25
17


In [ ]:
list_1=[1,2,3,4,5,6,7,8]
def list_deletion():
  del list_1[0]
  return list_1
def list_appendd():
  list_1.append(40)
  return list_1
list_deletion()
list_appendd()
print(list_1)

[2, 3, 4, 5, 6, 7, 8, 40]


In [ ]:
s=input("Enter a sentence ")
c=1
length=len(s)
def frequency():
  c=1
  for i in range(0,length):
    if s[i]==' ':
      c=c+1
  print(c)
frequency()

Enter a sentence yewfty wuyegruy wygeruy
3


In [ ]:
s=input("Enter a word ")
def frequency():
  length=len(s)
  print(length)
frequency()

Enter a word Bhavya
6


In [ ]:
def prime(n):
  c=0
  for i in range(1,n+1):
    if(n%i==0):
      c=c+1
  if(c==2):
    print("Number is Prime")
  else:
    print("Number is not Prime")
prime(2)

Number is Prime


In [ ]:
def fib(n):
  a=0
  b=1
  print(a)
  print(b)
  if(n>0):
    c=a+b
    a=b
    b=c
    print(c)
fib(7)

0
1
1


In [ ]:
def sum(list,n):
  if(n==0):
    return 0
  else:
    return (list[n-1]+sum(list,n-1))
sum([1,2,3,4,5,6,7,8,9],9)

45

In [ ]:
from functools import reduce
list_1=[2,3,5,6,10,12,14]
evens=list(filter(lambda n : n%2==0,list_1))
print(evens)
o1=list(map(lambda n:n*2,evens))
print(o1)
o2=reduce(lambda a,b:a+b,o1)
print(o2)

[2, 6, 10, 12, 14]
[4, 12, 20, 24, 28]
88


In [ ]:
list_1=[2,3,5,6,10,12,14]
evens=list(filter(lambda n : n%2==0,list_1))
odds=list(filter(lambda n : n%2!=0,list_1))
print(evens)
print(odds)

[2, 6, 10, 12, 14]
[3, 5]


In [ ]:
list_1=[2,3,5,6,10,12,14]
def count(list_1):
  ev=0
  od=0
  for i in list_1:
    if i%2==0:
      ev=ev+1
    else:
      od=od+1
  return ev,od
even,odd=count(list_1)
print(even,odd)

5 2


In [ ]:
%cd /content/drive/MyDrive/batch_53

/content/drive/MyDrive/batch_53


In [ ]:
!python -m calendar 2024

                                  2024

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7                1  2  3  4                   1  2  3
 8  9 10 11 12 13 14       5  6  7  8  9 10 11       4  5  6  7  8  9 10
15 16 17 18 19 20 21      12 13 14 15 16 17 18      11 12 13 14 15 16 17
22 23 24 25 26 27 28      19 20 21 22 23 24 25      18 19 20 21 22 23 24
29 30 31                  26 27 28 29               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     

In [ ]:
!python ans.py

Traceback (most recent call last):
  File "/content/drive/MyDrive/batch_53/ans.py", line 3, in <module>
    print(values.maximum(list_1))
NameError: name 'values' is not defined


In [ ]:
list_1=[10,8,22,36,12,47,21]
def maximum(num):
  maxi=0
  for i in list_1:
    if maxi<i:
      maxi=i
  return maxi
print(maximum(list_1))

47


In [ ]:
%cd /content/drive/MyDrive/lab-work

/content/drive/MyDrive/lab-work


In [ ]:
!ls

main.py  modular.py


In [ ]:
!python main.py

36100
Fibonacci Series :  0 1 1 2 3 5 8 13 21 34 
Maximum =  47
Minimum =  8


In [ ]:
!pip install tensorflow

In [ ]:
from keras.applications import ResNet50
model1=ResNet50()
model1.summary()

102967424/102967424 [==============================] - 1s 0us/step
Model: "resnet50"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 224, 224, 3)]        0         []                            
                                                                                                  
 conv1_pad (ZeroPadding2D)   (None, 230, 230, 3)          0         ['input_1[0][0]']             
                                                                                                  
 conv1_conv (Conv2D)         (None, 112, 112, 64)         9472      ['conv1_pad[0][0]']           
                                                                                                  
 conv1_bn (BatchNormalizati  (None, 112, 112, 64)         256       ['conv1_conv[0][0]']          
 on)                    

In [ ]:
!pip install pywhatkit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 2.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.2/171.2 kB 8.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.8/132.8 kB 16.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Created wheel for pyautogui: filename=PyAutoGUI-0.9.54-py3-none-any.whl size=37576 sha256=682433b16e60

In [ ]:
import time
for i in range(10):
  time.sleep(3)
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
try:
  age=int(input("Enter your age : "))
  print(age)
except(ValueError):
  print("Enter the number only")

Enter your age : 5
5


In [ ]:
class Point:
  def draw(self):
    print("draw the point")
  def coordinates(self):
    print("mention on x-y plane")
A = Point()
A.draw()
A.coordinates()

draw the point
mention on x-y plane


In [ ]:
def Abc(text):
  return text.upper()
def dff(text):
  return text.lower();
print(Abc("My name is Ram"))
name=Abc
print(name("My name is Bhavya"))
def greet(func):
  greeting=func("Welcome to the class")
  print(greeting)
greet(Abc)
greet(dff)

MY NAME IS RAM
MY NAME IS BHAVYA
WELCOME TO THE CLASS
welcome to the class


In [ ]:
class Employee:

  def __init__(self,n,d):
    print(n*d)
Employee(2,4)

8


In [ ]:
class Square:
  def area(self,s):
    print(s * s)
  def perimeter(self,s):
    print(4 * s)
R1=Square()
a=int(input("Enter the side of square : "))
R1.area(a)
R1.perimeter(a)

Enter the side of square : 4
16
16


In [ ]:
class Number:
  def table(self,n):
    for i in range(1,11):
      print(n*i)
R1=Number()
a=int(input("Enter the number : "))
R1.table(a)

Enter the number : 2
2
4
6
8
10
12
14
16
18
20


In [ ]:
class Employee:
  name="Bhavya"
  sapid=500122949
  def info(self):
    print(self.name,self.sapid)
E1=Employee()
E1.info()

Bhavya 500122949


In [ ]:
class Employee:
  name="Bhavya"
  sapid=500122949
  def info(self):
    print(self.name,self.sapid)
  class Activity:
    def info(self):
      print("Hello")
E1=Employee.Activity()
E1.info()

Hello


In [ ]:
class Employee:
  name="Bhavya"
  sapid=500122949
  def info(self):
    print(self.name,self.sapid)
    self.a=self.Activity
  class Activity:
    def info(self):
      print("Hello")
E1=Employee()
E1.info()
E2=E1.a()
E2.info()

Bhavya 500122949
Hello


In [ ]:
class Assistant:
  def __init__(self,name,id):
    self.name=name
    self.id=id

In [ ]:
class A:
  def __init__(self,x,y):
    self.name=x
    self.sapid=y
    print("I am inside the init of class A")
  def showA(self):
    print("Inside show of A")
  def attrib(self):
    print(self.name, self.sapid)
a1=A("Bhavya",500122949)
a1.name
a1.showA()
a1.attrib()

I am inside the init of class A
Inside show of A
Bhavya 500122949


In [ ]:
import abc
from abc import ABC
class A(ABC):
  def show(self):
    print("Show-off")
  def show2(self):

In [ ]:
class Shape:
  def __init__(self):
    self.sq = self.Square(10)
  def area(self):
    return 0;
  class Square(Shape):
    def __init__(self, length):
      self.l = length
    def area(self):
      print(self.l * self.l)
s1 = Shape()
s1.sq.area()

100


In [ ]:
import abc
from abc import ABC, abstractmethod
class Employee(ABC):
  @abstractmethod
  def name(self):
    pass
  def sapid(self):
    pass
  def email(self):
    pass
  def deptt(self):
    print("I am in CSE department")

class Professor(Employee):
  def __init__(self, iname, sapid, mail):
    self.i = iname
    self.sap = sapid
    self.mail = mail
  def name(self):
    print(self.i)
  def sapid(self):
    print(self.sap)
  def email(self):
    print(self.mail);
p1 = Professor("Bhavya","500122949","abc@123")
p1.name()
p1.sapid()
p1.email()

Bhavya
500122949
abc@123


In [ ]:
class Employee:
  def __init__(self, name):
    self.n = name;
  def __deptt(self):   #private
    print("I am in SOCS");
  def _deptt(self):    #protected
    print("Bhavya");

In [ ]:
!pip install numpy

In [ ]:
!pip install pandas

In [ ]:
!pip install seaborn

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
l1 = [1,2,4,8,99,50,34,21,0,3]

In [ ]:
print(type(l1))

<class 'list'>


In [ ]:
a1 = np.array(l1)
print(a1)

[ 1  2  4  8 99 50 34 21  0  3]


In [ ]:
print(type(a1))

<class 'numpy.ndarray'>


In [ ]:
t1 = (0,2,3,4,6,88,32)
a2 = np.array(t1)
print(a2)

[ 0  2  3  4  6 88 32]


In [ ]:
a2[::]

array([ 0,  2,  3,  4,  6, 88, 32])

In [ ]:
a2[6:]

array([32])

In [ ]:
a2[3:5]

array([4, 6])

In [ ]:
a3 = np.arange(0,20).reshape(4,5)
print(a3);

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
a4 = np.random.randint(0,1000,200).reshape(10,20)
print(a4)

[[ 91 563 865 942 298 488 831 356 302 186 484 272 787 573 752 500 540 175
  438 553]
 [127  69 890 602 415   2  25 630  90 722  67 463 689 876 440 949 621 903
  712 157]
 [568 537 665 112 695 166 944 764 848 758 555  39 629 290 507 630 247 198
  520 843]
 [371 429 291 622 209 751 586 592 294 428 823 466 505 439 593 840 202 543
  812 143]
 [889 968 755 703 153 535  35 760  81  59  53  61 394  60 531 528 735 456
  917 885]
 [526 992 679 558 358 133 661 630 516 973 185 372 221 104 285 176 106 152
  298 163]
 [499 165 231 189 664 808 466 348 310 455 431 654 353 707 867 396 129 248
  832 822]
 [854 299 446 841 522 844 583 725 308  61 367 326 585 712  62 456 354 697
  197   4]
 [228  97 669 771 586 329 315 875 340 831 485 710 733 270 645 546 956 375
  203 261]
 [899 442  21 371 292 106 761 785 204 565 786 892  68 122 284 598 408 538
   25 830]]


In [ ]:
a4[4:5,4:8]

array([[153, 535,  35, 760]])

In [ ]:
a4[-1: ,-1: ]

array([[830]])

In [ ]:
a4[9: ,9: ]

array([[565, 786, 892,  68, 122, 284, 598, 408, 538,  25, 830]])

In [ ]:
df = pd.DataFrame(data = np.arange(0,50).reshape(5,10),index = ["Row1","Row2","Row3","Row4","Row5"],columns = ["col1","col2","col3","col4","col5","col6","col7","col8","col9","col10"])
print(df)

      col1  col2  col3  col4  col5  col6  col7  col8  col9  col10
Row1     0     1     2     3     4     5     6     7     8      9
Row2    10    11    12    13    14    15    16    17    18     19
Row3    20    21    22    23    24    25    26    27    28     29
Row4    30    31    32    33    34    35    36    37    38     39
Row5    40    41    42    43    44    45    46    47    48     49


In [ ]:
print(df.head(2))

      col1  col2  col3  col4  col5  col6  col7  col8  col9  col10
Row1     0     1     2     3     4     5     6     7     8      9
Row2    10    11    12    13    14    15    16    17    18     19


In [ ]:
print(df.tail(2))

      col1  col2  col3  col4  col5  col6  col7  col8  col9  col10
Row4    30    31    32    33    34    35    36    37    38     39
Row5    40    41    42    43    44    45    46    47    48     49


In [ ]:
df = pd.DataFrame(data = np.arange(0,168).reshape(12,14),index = ["Row1","Row2","Row3","Row4","Row5"],columns = ["col1","col2","col3","col4","col5","col6","col7","col8","col9","col10"])
print(df)

In [ ]:
sns.pairplot(df, hue='Species')

In [ ]:
class Circle:
  def __init__(self, r):
    self.rad = r
  def getArea(self):
    self.A = (3.14) * self.rad * self.rad
    print(self.A)
  def getPerimeter(self):
    self.P = 2 * (3.14) * self.rad
    print(self.P)
Shape = Circle(4)
Shape.rad

4

In [1]:
import pandas as pd
import numpy as np

l1 = []
x = int(input("number of rows: "))
print('''sap id-->
first name-->
last name-->
subject -->
teacher-->
marks-->\n''')
for i in range(x):
    l1.append([])
    print("row", i+1)
    temp1 = int(input("-->"))
    l1[i].append(temp1)
    temp1 = input("-->")
    l1[i].append(temp1)
    temp1 = input("-->")
    l1[i].append(temp1)
    temp1 = input("-->")
    l1[i].append(temp1)
    temp1 = input("-->")
    l1[i].append(temp1)
    temp1 = int(input("-->"))
    l1[i].append(temp1)
df = pd.DataFrame(data=np.array(l1),columns=["sap id", "Fname", "Lname", "subject", "teacher", "marks"])
print(df)

number of rows: 2
sap id-->
first name-->
last name-->
subject -->
teacher-->
marks-->

row 1
-->500122949
-->Bhavya
-->Goyal
-->Python
-->Syed Sir
-->90
row 2
-->500122950
-->Bhavya
-->Goyal
-->C
-->Sir
-->90
      sap id   Fname  Lname subject   teacher marks
0  500122949  Bhavya  Goyal  Python  Syed Sir    90
1  500122950  Bhavya  Goyal       C       Sir    90
